services:
  weathergram:
    build: .
    volumes:
      - /database:database

    environment:
      - API_ID=...
      - API_HASH=...
      - BOT_TOKEN=...

      - DATABASE_URL=sqlite:////database/file.db

volumes:
  database:
